### ISSUE TITLE
文件大于100M时出现parts_num为float问题

### ISSUE THREAD

**Issue by goukunpeng** [liukangxu/cos-python3-sdk-v5#1]
cos_client.py,1185行，parts_num = file_size / part_size，应修改为parts_num = file_size // part_size

**Comment by liukangxu** [comment]
你好，感谢反馈！本项目诞生的原因是腾讯云在2018年仍未提供官方Python 3 SDK，鉴于目前官方SDK已经支持 Python 2.7 以及 Python 3.4，本项目的使命已经完成，因此不会再修复bug了，建议您使用官方Python SDK：https://cloud.tencent.com/document/product/436/12269
